### PR TITLE
Added optional files for the GSI soil analysis.

### LINKED ISSUE #12: New convinfo, anavinfo files for GSI soil analysis
Global_workflow PR [2263](https://github.com/NOAA-EMC/global-workflow/pull/2263) will add initial capability to include a soil analysis in the GSI. 

The soil analysis requires changes to the convinfo file (turning on the assimilation of T2m and q2m) and the anavinfo file (addition of relevant state variables to the various namelists). 

Examples of the new files are here on hera: 
/scratch2/BMC/gsienkf/Clara.Draper/2mDAfiles_gworkflow/

For the near-future, the global workflow will select the alternative *info files only when the soil analysis flag is selected. To complete that PR we will need to add the alternative *info files to the GSIfix directory.

### PR DESCRIPTION
**Pull request by ClaraDraper-NOAA**
Added two new files, as alternates for global_convinfo.txt and global_anavinfo.txt, for experiments using the new GSI soil analysis.

* new convinfo file (global_convinfo_2mObs.txt) turns on assimilation of 2m T and 2m q, and updates QC limits
* new anavinfo file ( global_anavinfo_soilanal.l127.txt) updates MetGuess for calculation of the 2m h(x), and adds enkf updating of soil moisture and soil temperature.

These files address GSI-fix issue [12](https://github.com/NOAA-EMC/GSI-fix/issues/12), and are required for global_workflow issue [1479](https://github.com/NOAA-EMC/global-workflow/issues/1479) / PR [2263](https://github.com/NOAA-EMC/global-workflow/pull/2263). 

I have incorporated @ADCollard's changes into for PR [11](https://github.com/NOAA-EMC/GSI-fix/issues/11) into my new files.

### CODE REVIEW

**Comment by RussTreadon-NOAA** [comment]
@ClaraDraper-NOAA , GSI-fix has no code manager or PR review team.   Who would you like to review the changes in this PR?  You may be able to add reviewers yourself.  I don't know.

**Comment by ClaraDraper-NOAA** [comment]
@RussTreadon-NOAA I'm not able to add reviewers. Jeff and Cathy would be good choices, since they did the associated GSI PR review. 

Also thanks for shepherding the GSI PR through.

**Review by jswhit2 — APPROVED** [review]

**Review by CatherineThomas-NOAA — APPROVED** [review]
I compared global_convinfo_2mObs.txt and global_convinfo.txt.  I see the turning on of T and q for subtypes 181, 183, and 187, along with changes to other values for those lines.  I also see the addition of uv 290 MetOp-C, which is part of Andrew’s PR.  I checked out his branch as well and confirmed that the uv change is identical to his PR.

I then compared the global_anavinfo files.  I see t2m and q2m added to the state vector and met_guess, as well as the soil moisture and soil temperature variables added to the EnKF control vector.  There are additional changes for CrIS that are identical to Andrew’s PR.  This soil DA PR also correctly includes the efsoi block that needs to be added back into Andrew’s PR.

Looks good to me, approve.

**Comment by RussTreadon-NOAA** [comment]
@ClaraDraper-NOAA , would you please update your branch, `ClaraDraper-NOAA:feature/soilanal`, with changes from the updated `develop`?   Once this is done, we can merge this PR into `develop`.

**Comment by ClaraDraper-NOAA** [comment]
> @ClaraDraper-NOAA , would you please update your branch, `ClaraDraper-NOAA:feature/soilanal`, with changes from the updated `develop`? Once this is done, we can merge this PR into `develop`.

Done. Thanks @RussTreadon-NOAA

**Review by RussTreadon-NOAA — APPROVED** [review]
Looks good to me.

Approve.

**Pull request merged**
