### PR TITLE
update anavinfo and convinfo for RRFS.

### PR DESCRIPTION
**Pull request by hu5970**
The update anavinfo and convinfo for RRFS to include more observation types and run with SDL/VDL on.

### CODE REVIEW

**Review by ShunLiu-NOAA — APPROVED** [review]

**Comment by xyzemc** [comment]
Does this mean there will be two anavinfo files for RRFS?

**Review by TingLei-NOAA — APPROVED** [review]

**Comment by RussTreadon-NOAA** [comment]
@ShunLiu-NOAA , let me know if you find that you can not merge this PR into `develop` after all reviews are complete.

**Comment by ShunLiu-NOAA** [comment]
> Does this mean there will be two anavinfo files for RRFS?

Yes. The two files are for RRFS regression test.

**Comment by ShunLiu-NOAA** [comment]
@RussTreadon-NOAA Thank you. Will let you know if I can't merge this PR to GSI-fix.

**Review by xyzemc — APPROVED** [review]

**Pull request merged**
