### PR TITLE
gfs.v16.3.9 updates to global_convinfo.txt and global_ozinfo.txt (#9)

### LINKED ISSUE #9: Fix file updates for gfs.v16.3.9
NCO implemented gfs.v16.3.9 effective 20230911 12Z.   See g-w issue [#1813](https://github.com/NOAA-EMC/global-workflow/issues/1813) for details.   This implementation changed fix files `global_convinfo.txt` and `global_ozinfo.txt`.  GSI PR [#613](https://github.com/NOAA-EMC/GSI/pull/613) provides additional documentation.

The operational GFS picks up GSI fix files from gerrit:GSI-fix.   The develop GSI picks up ASCII GSI fix files from [NOAA-EMC/GSI-fix](https://github.com/NOAA-EMC/GSI-fix).   

The changes made to `global_convinfo.txt` and `global_ozinfo.txt` committed to gerrit:GSI-fix must also be committed to NOAA-EMC/GSI-fix.   This issue is opened to document NOAA-EMC/GSI-fix updates to these two files.

### PR DESCRIPTION
**Pull request by RussTreadon-NOAA**
NCO implemented gfs.v16.3.9 at 12Z on 20230911.   gfs.v16.3.9 changed two GSI fix files:  `global_convinfo.txt` and `global_ozinfo.txt`.   Details of the changes are found in issue #9.   This PR is opened to capture these updates in the authoritative NOAA-EMC/GSI-fix repository.

Fixes #9

### CODE REVIEW

**Comment by RussTreadon-NOAA** [comment]
@ADCollard , @HaixiaLiu-NOAA , @XuanliLi-NOAA

NCO implemented gfs.v16.3.9 yesterday.   The updates to `global_convinfo.txt` and `global_ozinfo.txt` have been committed to gerrit:GSI-fix.   We need to commit the same updates to NOAA-EMC/GSI-fix.   That's what this PR does.   

When you have time would you review and confirm that the changes I made to `global_convinfo.txt` and `global_ozinfo.txt` are correct?  

Thank you.

**Comment by XuanliLi-NOAA** [comment]
Yes, the change to global_convinfo.txt is correct.

**Comment by RussTreadon-NOAA** [comment]
> Yes, the change to global_convinfo.txt is correct.

Thank you, @XuanliLi-NOAA , for the confirmation.  Would you please indicate this by approving this PR?

**Review by XuanliLi-NOAA — APPROVED** [review]
global_convinfo.txt looks to me!

**Comment by RussTreadon-NOAA** [comment]
A diff of the operational gfs.v16.3.9 `global_ozinfo.txt` and the same named file in `release/gfs.v16.3.9` shows no difference
```
russ.treadon@dlogin08:/lfs/h2/emc/da/noscrub/russ.treadon/git/gsi-fix/gfs.v16.3.9> git branch
  develop
* release/gfs.v16.3.9
* 
russ.treadon@dlogin08:/lfs/h2/emc/da/noscrub/russ.treadon/git/gsi-fix/gfs.v16.3.9> diff /lfs/h1/ops/prod/packages/gfs.v16.3.9/fix/fix_gsi/global_ozinfo.txt ./global_ozinfo.txt

russ.treadon@dlogin08:/lfs/h2/emc/da/noscrub/russ.treadon/git/gsi-fix/gfs.v16.3.9> 
```


Given this move forward with merge of `release/gfs.v16.3.9` into `develop`.

**Pull request merged**
